package application.lexer;

public enum TokenType {
    // Símbolos
    ABRE_PAREN, FECHA_PAREN,
    ABRE_CHAVE, FECHA_CHAVE,
    ABRE_COLCHETE, FECHA_COLCHETE,
    VIRGULA, ATRIBUICAO,
    SOMA, SUBTRACAO, MULTIPLICACAO, DIVISAO, MODULO,
    INCREMENTO, DECREMENTO,
    SOMA_ATRIBUICAO, SUBTRACAO_ATRIBUICAO,
    MULTIPLICACAO_ATRIBUICAO, DIVISAO_ATRIBUICAO,
    MODULO_ATRIBUICAO,

    // Comparação
    IGUAL, DIFERENTE,
    MAIOR, MAIOR_IGUAL,
    MENOR, MENOR_IGUAL, PONTO_VIRGULA,

    // Literais
    IDENTIFICADOR,
    LITERAL_NUMERO,
    LITERAL_TEXTO,
    LITERAL_LOGICO,

    // Palavras-chave
    MOSTRAR, FORMATAR, LER,
    SE, SENAO, ENQUANTO, PARA,
    FUNC, 

    // Tipos primitivos
    NUMERO, TEXTO, LOGICO, LISTA,
    LONG, SHORT, UNSIGNED,
    DOUBLE, VOID,

    // Operadores lógicos
    E, OU, NAO_LOGICO,

    // Outros
    ERRO,
    EOF, RETORNAR
}